In [5]:
import pandas as pd

# Replace 'your_file.parquet' with the path to your Parquet file
df = pd.read_parquet('../data/raw/NREL/100018-9.parquet')

# Display the first few rows of the dataframe
df.head()

,timestamp,out.electricity.ceiling_fan.energy_consumption,out.electricity.ceiling_fan.energy_consumption_intensity,out.electricity.clothes_dryer.energy_consumption,out.electricity.clothes_dryer.energy_consumption_intensity,out.electricity.clothes_washer.energy_consumption,out.electricity.clothes_washer.energy_consumption_intensity,out.electricity.cooling.energy_consumption,out.electricity.cooling.energy_consumption_intensity,out.electricity.cooling_fans_pumps.energy_consumption,...,out.total.lrmer_midcase_15__electricity.co2e_kg,out.total.lrmer_midcase_15__fuel_oil.co2e_kg,out.total.lrmer_midcase_15__natural_gas.co2e_kg,out.total.lrmer_midcase_15__propane.co2e_kg,out.total.lrmer_midcase_15.co2e_kg,out.total.lrmer_midcase_25__electricity.co2e_kg,out.total.lrmer_midcase_25__fuel_oil.co2e_kg,out.total.lrmer_midcase_25__natural_gas.co2e_kg,out.total.lrmer_midcase_25__propane.co2e_kg,out.total.lrmer_midcase_25.co2e_kg
bldg_id,,,,,,,,,,,,,,,,,,,,,
100018,2018-01-01 01:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.048103,0.0,0.000000,0.0,0.048103,0.034972,0.0,0.000000,0.0,0.034972
100018,2018-01-01 02:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.138504,0.0,0.127655,0.0,0.266159,0.100512,0.0,0.127655,0.0,0.228166
100018,2018-01-01 03:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.241865,0.0,0.289083,0.0,0.530948,0.175236,0.0,0.289083,0.0,0.464315
100018,2018-01-01 04:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.096175,0.0,0.000000,0.0,0.096175,0.070425,0.0,0.000000,0.0,0.070425
100018,2018-01-01 05:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.050403,0.0,0.000000,0.0,0.050403,0.036827,0.0,0.000000,0.0,0.036827

In [23]:
import pandas as pd

df = pd.read_parquet('../data/raw/NREL/baseline.parquet')

bldg_100018 = df.loc[100018]

df.head()

,applicability,in.sqft,weight,in.ahs_region,in.aiannh_area,in.area_median_income,in.ashrae_iecc_climate_zone_2004,in.ashrae_iecc_climate_zone_2004_2_a_split,in.bathroom_spot_vent_hour,in.battery,...,out.fuel_oil.total.lrmer_high_re_cost_2030_boxavg.co2e_kg,out.natural_gas.clothes_dryer.energy_consumption,out.natural_gas.clothes_dryer.energy_consumption_intensity,out.site_energy.total.energy_consumption,out.site_energy.total.energy_consumption_intensity,upgrade,metadata_index,in.representative_income,out.bills.all_fuels.usd,out.energy_burden.percentage
bldg_id,,,,,,,,,,,,,,,,,,,,,
1,True,3310.0,63.075295,Non-CBSA Pacific,No,150%+,3C,3C,Hour5,None,...,0.0,0.0,0.0,13536.659660,4.089625,0,0,149501.0,2669.71,1.79
2,True,1698.0,63.075295,Non-CBSA South Atlantic,No,Not Available,2A,"2A - FL, GA, AL, MS",Hour0,None,...,0.0,0.0,0.0,8306.220271,4.891767,0,1,NaN,1164.51,NaN
3,True,1138.0,63.075295,"CBSA Los Angeles-Long Beach-Anaheim, CA",No,60-80%,3B,3B,Hour20,None,...,0.0,0.0,0.0,6161.819250,5.414604,0,2,63747.0,1504.42,2.36
4,True,1698.0,63.075295,Non-CBSA East North Central,No,60-80%,5A,5A,Hour18,None,...,0.0,0.0,0.0,44290.951622,26.084188,0,3,27012.0,4494.08,16.64
5,True,3310.0,63.075295,Non-CBSA East South Central,No,Not Available,2A,"2A - FL, GA, AL, MS",Hour22,None,...,0.0,0.0,0.0,14868.081532,4.491868,0,4,NaN,2035.52,NaN

In [30]:
filtered_df = df[df['in.pv_system_size'].notna()]
columns_to_exclude = filtered_df.filter(like='out.').columns.tolist() + ['column_name_1', 'column_name_2']
filtered_df = filtered_df.drop(columns=columns_to_exclude)

filtered_df.head()

,applicability,in.sqft,weight,in.ahs_region,in.aiannh_area,in.area_median_income,in.ashrae_iecc_climate_zone_2004,in.ashrae_iecc_climate_zone_2004_2_a_split,in.bathroom_spot_vent_hour,in.battery,...,in.water_heater_fuel,in.water_heater_in_unit,in.weather_file_city,in.weather_file_latitude,in.weather_file_longitude,in.window_areas,in.windows,upgrade,metadata_index,in.representative_income
bldg_id,,,,,,,,,,,,,,,,,,,,,
1,True,3310.0,63.075295,Non-CBSA Pacific,No,150%+,3C,3C,Hour5,None,...,Natural Gas,Yes,Salinas Muni AP,36.667,-121.600,F15 B15 L15 R15,"Double, Low-E, Non-metal, Air, M-Gain",0,0,149501.0
2,True,1698.0,63.075295,Non-CBSA South Atlantic,No,Not Available,2A,"2A - FL, GA, AL, MS",Hour0,None,...,Natural Gas,Yes,Tallahassee Regional Ap Isis,30.380,-84.370,F12 B12 L12 R12,"Single, Clear, Metal",0,1,NaN
3,True,1138.0,63.075295,"CBSA Los Angeles-Long Beach-Anaheim, CA",No,60-80%,3B,3B,Hour20,None,...,Electricity,Yes,Jack Northrop Fld H,33.920,-118.330,F15 B15 L15 R15,"Double, Clear, Metal, Air",0,2,63747.0
4,True,1698.0,63.075295,Non-CBSA East North Central,No,60-80%,5A,5A,Hour18,None,...,Electricity,Yes,Muncie-Delaware County Rgnl AP,40.233,-85.400,F9 B9 L9 R9,"Single, Clear, Non-metal, Exterior Clear Storm",0,3,27012.0
5,True,3310.0,63.075295,Non-CBSA East South Central,No,Not Available,2A,"2A - FL, GA, AL, MS",Hour22,None,...,Electricity,Yes,Mobile Downtown AP,30.633,-88.067,F18 B18 L18 R18,"Single, Clear, Non-metal, Exterior Clear Storm",0,4,NaN

In [39]:
bldg_filtered = df[df['in.pv_system_size'].notna()]
bldg_filtered = bldg_filtered[bldg_filtered["in.census_region"] == "West"]
columns_to_exclude = bldg_filtered.filter(like='out.').columns.tolist() + ['in.bathroom_spot_vent_hour', 'applicability']
bldg_filtered = bldg_filtered.drop(columns=columns_to_exclude)

bldg_filtered.head().to_csv("../data/processed/bldg_filtered_temp.csv")

In [40]:
# Select all columns with the prefix "in."
filtered_columns = bldg_100018.filter(like='in.')

# Display the first few rows of the filtered columns
print(filtered_columns.head())

in.sqft                                                  1228.0
in.ahs_region                       Non-CBSA East North Central
in.aiannh_area                                               No
in.area_median_income                             Not Available
in.ashrae_iecc_climate_zone_2004                             5A
Name: 100018, dtype: object